### ISSUE TITLE
WP5: PHP Notice:  WP_Block_Type_Registry::register was called <strong>incorrectly</strong>

### ISSUE THREAD

**Issue by lordspace** [Automattic/syntaxhighlighter#104]
`[04-Feb-2019 19:24:23 UTC] PHP Notice:  WP_Block_Type_Registry::register was called <strong>incorrectly</strong>. Block type "syntaxhighlighter/code" is already registered. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 5.0.0.) in /var/www/vhosts/example.com/main/htdocs/wp-includes/functions.php on line 4231
`

**Comment by Viper007Bond** [comment]
Hmm, I can't reproduce this and I'm only calling the function once:

https://github.com/Viper007Bond/syntaxhighlighter/blob/v3.5.0/syntaxhighlighter.php#L77

Only thing I can suggest is disabling all other plugins and perhaps reinstalling mine.

**Comment by lordspace** [comment]
Thanks for looking into it. Oh, I just remembered that one of my plugins was loading yours.
Maybe I have to rethink the integration.

**Comment by Viper007Bond** [comment]
Heh, that'd probably do it. You're likely initializing a second copy of my plugin.

I guess I need to update my plugin to make it a singleton, like I do with my others:

https://github.com/Viper007Bond/regenerate-thumbnails/blob/v3.1.0/regenerate-thumbnails.php#L554-L566

**Comment by lordspace** [comment]
Thanks Alex for the idea.
