### ISSUE TITLE
NEW REPO: https://github.com/Automattic/syntaxhighlighter

### ISSUE THREAD

**Issue by donnchawp** [Automattic/syntaxhighlighter#111]
I have forked Alex's plugin and we're continuing development in a new repository. You can find it at https://github.com/Automattic/syntaxhighlighter

A new release was made today so this repository is out of date now. 

If you have any issues or PRs to submit please use the new repository.

**Comment by alexsanford** [comment]
The repo has now been transferred, and properly redirects from the old URL 👍
