### ISSUE TITLE
Switch from Visual to Text creates new lines

### ISSUE THREAD

**Issue by AndreaBarghigiani** [Automattic/syntaxhighlighter#128]
Yesterday I was working on #127 but I noticed a different problem that is affecting all my WordPress installations.

I've tried to paste some code in the Text window of the Classic Editor and when I switch to Visual my code gets messed. In Visual editor I see new lines coming up as you describe better below.

### Problems with spaces an lines
Let's say for example that I need to paste the following code that I copied from a code editor:
```php
<?php get_header(); ?>
 
  <div id="primary" class="site-content">
    <div id="content" role="main">
 
      <?php while ( have_posts() ) : the_post(); ?>
 
          <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
 
            <header class="entry-header">
              <h1 class="entry-title"><?php the_title(); ?></h1>
            </header>
 
            <div class="entry-content">
              <?php the_content(); ?>
            </div><!-- .entry-content -->
 
          </article><!-- #post -->
 
      <?php endwhile; // end of the loop. ?>
 
    </div><!-- #content -->
  </div><!-- #primary -->
 
<?php get_sidebar(); ?>
<?php get_footer(); ?>
```

I paste this code in the *Text* tab and then I switch to *Visual* I get the following:
```php
&lt;?php get_header(); ?&gt;
 
  
<div id="primary" class="site-content">
    
<div id="content" role="main">
 
      &lt;?php while ( have_posts() ) : the_post(); ?&gt;
 
          
<article id="post-&lt;?php the_ID(); ?&gt;" &lt;?php post_class(); ?&gt;>
 
            
<header class="entry-header">
              
<h1 class="entry-title">&lt;?php the_title(); ?&gt;</h1>

            </header>

 
            
<div class="entry-content">
              &lt;?php the_content(); ?&gt;
            </div>

<!-- .entry-content -->
 
          </article>

<!-- #post -->
 
      &lt;?php endwhile; // end of the loop. ?&gt;
 
    </div>

<!-- #content -->
  </div>

<!-- #primary -->
 
&lt;?php get_sidebar(); ?&gt;
&lt;?php get_footer(); ?&gt;
```

Besides the angle brackets that get changed only if they're close to the question mark (#127), do you notice the new lines? Also for the HTML comments, they're put in a new line.

Do you have an idea of why this is happening?

I have tested this code in many browsers and different WordPress versions, all of them were using the SyntaxHighlighter Evolved v3.5.2

I am trying to roll back a few versions of the plugin and I'll update the issue.

**Updates:**
* found a similar [issue on WP.org forum](https://wordpress.org/support/topic/problem-with-line-breaks-2/) with no answers

**Comment by AndreaBarghigiani** [comment]
Things get stranger and stranger... 

So I've tested version 3.4.2 on a site and the new line problem persists **but** I've noticed different behavior in my tests.

**Not all code is affected, even if they have the same hidden character**
The new line does not affect any block code. For example if I use a snippet from the [syntaxhighlighter.php](https://github.com/Automattic/syntaxhighlighter/blob/master/syntaxhighlighter.php) of this same plugin no new lines gets created.

If I test the following I get new lines:
```html
<div>
	<h1>Hello World</h1>
</div>
```

I've checked for hidden characters with a simple online tool but as you can see from the image there is no difference for the ending characters.

![syntax-new-lines](https://user-images.githubusercontent.com/190159/76855116-b6193880-6850-11ea-81e0-5dfe7a8cf4b8.png)

 **New lines each time I switch between Text and Visual**
Also while testing I noticed that the lines get added **each time** I switch from Visual to Test 🤔

![syntax-new-lines-after-switch](https://user-images.githubusercontent.com/190159/76855631-ced61e00-6851-11ea-9776-da97808b8475.png)

As before, I was thinking that it was because there were hidden characters but that's not true.

Does anyone have any idea?

**Comment by alexsanford** [comment]
I was also able to reproduce this, specifically, seeing extra newlines when switching from "Text" to "Visual" (and more newlines every time).

**Comment by renatho** [comment]
Hey @AndreaBarghigiani !

Thank you for contributing to the project bringing this issue!

If you want, you can test this PR to check if it works properly in your end. https://github.com/Automattic/syntaxhighlighter/pull/139
