### ISSUE TITLE
shBrushYaml.js missing

### ISSUE THREAD

**Issue by Siytek** [Automattic/syntaxhighlighter#135]
I updated in Wordpress and it did not install `shBrushYaml.js` so my Yaml formatting was broken following the update. Manually copying the file from the repo fixed it for me but thought I would mention it.

Cheers, great plug-in!

**Comment by babelshift** [comment]
Noticed the same. Upon updating and switching a block to YAML, the highlighting completely reverted to a normal code block and rendered as preformatted text.

**Comment by renatho** [comment]
@Siytek, thank you for let us know! We just released a new version with the fix.

Cheers!
