### ISSUE TITLE
Syntax highlighting for XML broken for Authors

### ISSUE THREAD

**Issue by eugenschindler** [Automattic/syntaxhighlighter#142]
When an author makes a syntax highlighter block and sets it to XML/XHTML/... then the highlighting is completely broken and even the text is not displayed properly.
If I set the same user to editor instead of author, the highlighting suddenly works.

I didn't check other languages than XML, but they may have the same problem.

Using WordPress 5.4.

**Comment by alexsanford** [comment]
I can reproduce this for XML. For example, when I add the following code to a SyntaxHighlighter Code block in the Block Editor as an author:

```xml
<something />
<another />
```

Then I see this on the frontend:

<img width="624" alt="Screen Shot 2020-05-13 at 13 49 24" src="https://user-images.githubusercontent.com/842193/81841269-b45eaf00-9539-11ea-9a1f-52a6acb0a3a9.png">

When I change the user's role to Editor, and then change the block and save it, I see the following on the frontend:

<img width="627" alt="Screen Shot 2020-05-13 at 13 53 28" src="https://user-images.githubusercontent.com/842193/81841633-45ce2100-953a-11ea-8083-34b45028f347.png">

**Comment by donnapep** [comment]
This was fixed by https://github.com/Automattic/syntaxhighlighter/pull/160.
