### ISSUE TITLE
Empty div and no additional class added to code block

### ISSUE THREAD

**Issue by itsmereal** [Automattic/syntaxhighlighter#146]
When the syntax highlighter block is used, a div is generated without any class or attribute to select it. Also the additional classes do not appear in frontend when added to the block's additional class(es) field.

<img width="431" alt="Screen Shot 2020-05-04 at 12 10 38 PM" src="https://user-images.githubusercontent.com/3238960/80940089-79090580-8e00-11ea-9ad7-983175065330.png">
<img width="277" alt="Screen Shot 2020-05-04 at 12 10 12 PM" src="https://user-images.githubusercontent.com/3238960/80940092-7ad2c900-8e00-11ea-9390-be1efdb1c7f9.png">

**Comment by alexsanford** [comment]
Can you double-check that the additional CSS class isn't being added? That functionality was added in the latest version. Could you make sure you're on version 3.5.4 and confirm this?

As for the additional div, are there any problems that is causing? Or do you just need the ability to select a wrapper around the block (which should be fixed in the latest version)?

**Comment by itsmereal** [comment]
> Can you double-check that the additional CSS class isn't being added? That functionality was added in the latest version. Could you make sure you're on version 3.5.4 and confirm this?

I just tested it once more. With the default theme, the latest WordPress, and plugin version (3.5.4) installed.

<img width="793" alt="Screen Shot 2020-05-13 at 10 24 51 PM" src="https://user-images.githubusercontent.com/3238960/81838939-a96f4300-9568-11ea-8dc9-7aa8cea6d400.png">

> As for the additional div, are there any problems that is causing? Or do you just need the ability to select a wrapper around the block (which should be fixed in the latest version)?

I think it would be best if we could add the additional class in there or remove it. 

Thanks!
