### ISSUE TITLE
Create package script for deploys

### ISSUE THREAD

**Issue by renatho** [Automattic/syntaxhighlighter#147]
To make the deploy easier and prevent mistakes, we could create a script to generate a folder with the built plugin to upload.

Maybe we could do it based on https://github.com/Automattic/sensei/blob/master/gulpfile.js. Or create a new script for that.

**Comment by renatho** [comment]
See also: https://github.com/Automattic/regenerate-thumbnails/issues/100

**Comment by merkushin** [comment]
I found that in Sensei gulpfile was replaced with adding scripts to composer.json+package.json (https://github.com/Automattic/sensei/pull/3561).
So I'm going to do it the same way.
