### ISSUE TITLE
& ampersand sign gets transformed into HTML entities

### ISSUE THREAD

**Issue by adnanafzal565** [Automattic/syntaxhighlighter#155]
Can you please fix this ?
& is converted into HTML entities.

Thanks.

**Comment by jacobweber** [comment]
Sounds like #151 maybe?

**Comment by alexsanford** [comment]
@adnanafzal565 can you provide some more detail? Is this the same problem as described in #151 ? If not, how is it different?

**Comment by adnanafzal565** [comment]
It was fixed by calling htmlspecialchars() function.
