### ISSUE TITLE
How to get a better appearance?

### ISSUE THREAD

**Issue by dausruddin** [Automattic/syntaxhighlighter#157]
Hi. Referring to this screenshot
![image](https://user-images.githubusercontent.com/5763466/87055728-4ed82780-c237-11ea-88d1-c3d11473e158.png)
It is quite ugly. Especially if you got a lot of that in your writing. 

Is there any way to put some padding? Also is it possible to get more light themes too? My blog has white background. It is hard to read if I use light theme on this plugin because everything seems to blend together and with dark themes, it look like in the screenshot.

Thanks.

**Comment by alexsanford** [comment]
Hi there.

Please see the settings page (Settings > SyntaxHighlighter) for more theme options. For further customization you can use custom CSS. The settings page also allows you to set an additional CSS class on the container if that makes it easier.

Closing this, as this repo is reserved for reproducible bugs or clear enhancement requests. Feel free to post future support questions in the [plugin support forums](https://wordpress.org/support/plugin/syntaxhighlighter/) 🙂
