### ISSUE TITLE
Output from putty

### ISSUE THREAD

**Issue by fernandoch777** [Automattic/syntaxhighlighter#167]
When I copy text from a putty terminal which I believe uses courier new font and I paste it in wordpress, the text and columns are not aligned.

Is there a way to solve this?

Thanks

**Comment by yscik** [comment]
Resolved in https://wordpress.org/support/topic/bad-displaying-copying-from-terminal/#post-13640923 :

There could be a difference in how wide the terminal and the browser display TAB characters. To adjust the tab character size with CSS:

`.syntaxhighlighter { tab-size: 4; }`
