### ISSUE TITLE
Underscore character not visible in last line of code

### ISSUE THREAD

**Issue by funbeedev** [Automattic/syntaxhighlighter#168]
###  The issue:
When viewing code blocks on my Firefox browser, if the last line of code includes an underscore character, the underscore is not visible. 
The zoom percentage on the browser is a factor in whether the issue is present. The underscore will become visible at some zoom percentages < 100%. But it's an issue at zoom >=100%.
To ensure the underscore is visible I need to a new line. Either a new line with actual code or a new line with at least one space character. 

I tested this on a Chrome browser (v 83.0.4103.61) and it doesn't seem to be an issue there.

Perhaps more padding is needed at the bottom of the last line of code to improve readability in certain configurations?

### My setup:
Browser is Mozilla Firefox for Ubuntu 81.0 (64-bit)
SyntaxHighlighter Evolved v3.5.5

### Screenshots: 
Shows the issue described and my SyntaxHighlighter configuration in WordPress.
![Screenshot_SyntaxHighlighter_Underscore_Problem](https://user-images.githubusercontent.com/66768334/95920115-b9ed4900-0da6-11eb-9104-55cede95afed.png)
![Screenshot_SyntaxHighlighter_Wordpress_Settings](https://user-images.githubusercontent.com/66768334/95920116-ba85df80-0da6-11eb-806e-5bc5d39f83e9.png)

Can provide more info if needed. Thanks.

**Comment by yscik** [comment]
Thanks for the report!
What Wordpress theme are you using? I wasn't able to reproduce in Firefox, but font rendering can also depend on the OS. 

For some investigation, can you open the browser's Developer tools (F12), find the line or code tag with Inspect Element, and try changing some spacing styles, like turning off `line-height`. Also try adding `padding: 10px !important` to the `<td class="code">` tag. That could allow us to see if this can be fixed with adjusting spacing.

**Comment by funbeedev** [comment]
@yscik 
My Wordpress theme is [Harrison](https://wordpress.org/themes/harrison/).

If I inspect Element I can confirm turning off `line-height` will allow me to see the underscore character.
It also works if I add `padding:10px !important`

Since noticing this issue I've also come across another Wordpress site using a different theme to mine that uses syntax highlighter and the underscore character on the last line of code wasn't rendering properly for me.

**Comment by yscik** [comment]
Thanks for checking! We will look into adding padding for these blocks (#131), which should fix this issue then.
