### ISSUE TITLE
collapse appears to be broken

### ISSUE THREAD

**Issue by pjcigan** [Automattic/syntaxhighlighter#17]
Hello, I noticed an interesting problem recently.  After updating to v3.1.7, the collapse function seems to have broken.  Specifically, if I remove the collapse argument from my code blocks, they show up, and if I leave collapse in, the code disappears completely.  Manually setting light="false" and toolbar="true" in the code header doesn't affect anything.  (I also tried manually setting collapse="false" as a test, and that worked fine.)  Setting the default behavior to collapse=true in the settings pane makes all code disappear.  

Do you have any ideas or workarounds? 
Cheers,
Phil

**Comment by pjcigan** [comment]
I tried rendering with WP SyntaxHighlighter as well, and I find the same problem.  So maybe it's a problem that the base SyntaxHighlighter code has with the newest Wordpress version?

**Comment by alexsanford** [comment]
This appears to have been fixed as it is no longer reproducible.
