### ISSUE TITLE
Encoding issue with square brackets

### ISSUE THREAD

**Issue by alexsanford** [Automattic/syntaxhighlighter#191]
Testing on [v3.6.0-beta.1](https://github.com/Automattic/syntaxhighlighter/releases/tag/v3.6.0-beta.1).

### Steps to Reproduce
1. Create a new post.
2. Add a SyntaxHighlighter block.
3. Add some code that includes square brackets (`[` and `]`).
4. Save and load on the frontend.

### What I Expected

The square brackets to display properly.

### What Happened Instead

The square brackets are encoded:

<img width="1217" alt="Screen Shot 2021-02-12 at 15 48 21" src="https://user-images.githubusercontent.com/842193/107815417-4450b400-6d6b-11eb-9219-0156cc696988.png">

**Comment by renatho** [comment]
After talking with @alexsanford, we identified it probably was a build issue. So we're closing it for now.
