### ISSUE TITLE
Add list of supported tags

### ISSUE THREAD

**Issue by roman-mueller** [Automattic/syntaxhighlighter#207]
### Steps to Reproduce
1. Go to 'Settings page'
2. Try to figure out which tags are supported
3. Click on the link "Click here for a list of valid tags (under "aliases")."
4. Notice that the page displayed is some sort of PDF compression service now

### What I Expected
I wanted to figure out if there is a JSON tag.
The "Click here for a list of valid tags" link points to http://alexgorbatchev.com/SyntaxHighlighter/manual/brushes/ which now gets redirected to https://gogopdf.com/blog/Alex-Gorbatchev-And-gogopdf-Turn-Raw-Javascript-To-A-PDF-Service
It looks like the domain was registered by another organization. 
It may be necessary to remove all references to it from this repository.

### PHP / WordPress / SyntaxHighlighter Evolved version

SyntaxHighlighter Evolved 3.6.0

**Comment by MrYossu** [comment]
Having just come here with a similar question, I did discover that you can work out what languages are supported by looking at what [brushes are included in the source code](https://github.com/Automattic/syntaxhighlighter/tree/master/syntaxhighlighter3/scripts).

I agree that a list on the settings page would be useful, but this should get you going in the meantime. And no, it doesn't look like there is support for  JSON.
