### ISSUE TITLE
Default language snippet not working

### ISSUE THREAD

**Issue by cena** [Automattic/syntaxhighlighter#256]
We (@renatho :)) previously provided a snippet to set the default languge (vs. plain text) in this forum post:

https://wordpress.org/support/topic/how-to-set-a-default-language-parameter/

This no longer working (confirmed).

Can we update it?

**Comment by gikaragia** [comment]
Hey @cena not sure if this snippet was ever working but I think that there is a chance that it didn't.

In any case, tried modifying it a bit to make it work but couldn't. They could probably achieve the same result by using block variations or a JS filter in the frontend but I don't think that offering such a customization is inside the scope of our support.
