### ISSUE TITLE
Syntaxhighlighter block broken on Wordpress 6.4.1

### ISSUE THREAD

**Issue by mainmind83** [Automattic/syntaxhighlighter#267]
### Steps to Reproduce
1. Go to editor
2. Click on add
...

### What Happened Instead
"Your site doesn’t include support for the SyntaxHighlighter Evolved block. You can try installing the block, convert it to a Custom HTML block, or remove it entirely."

### PHP / WordPress / SyntaxHighlighter Evolved version
Wordpress 6.4.1
Theme Radiate - 1.4.1
SyntaxHighlighter Evolved version 3.6.2

### Browser / OS version
Chrome 119.0.6045.124 / Win 11 (10.0.22631.2428)

### Screenshot / Video
Same problem: https://wordpress.org/support/topic/your-site-doesnt-include-support-for-the-syntaxhighlighter-evolved-block-2/

![image](https://github.com/Automattic/syntaxhighlighter/assets/18678468/744734b8-c25d-4488-96ab-2583b24e05be)

**Comment by mainmind83** [comment]
Deprecated: Creation of dynamic property SyntaxHighlighter::$brush_names is deprecated in C:\inetpub\vhosts\example.com\httpdocs\blog\wp-content\plugins\syntaxhighlighter\syntaxhighlighter.php on line 248

Deprecated: Creation of dynamic property SyntaxHighlighter::$specialchars is deprecated in C:\inetpub\vhosts\example.com\httpdocs\blog\wp-content\plugins\syntaxhighlighter\syntaxhighlighter.php on line 326

**Comment by yscik** [comment]
[Lodash is no longer being loaded in Gutenberg](https://github.com/WordPress/gutenberg/pull/52571)

We need to list it as a dependency or remove it's usage from this plugin too.

<img src=https://i.imgur.com/yGyC81yl.png>
