### ISSUE TITLE
Nested shortcode problem

### ISSUE THREAD

**Issue by janikvonrotz** [Automattic/syntaxhighlighter#32]
Hi,

Can somebody help me with this issue:

```
[code]

[xml]

[/code]
```

output:

```
1
```

should be:

```
[xml]
```

this works:

```
[code]

[[xml]]

[/code]
```

It seems to be the same issue as here: https://github.com/Viper007Bond/syntaxhighlighter/issues/26
Instead of [c] it's [xml].

Is there way to fix f.g. tell Wordpress not to parse shortcodes inside code blocks?

The source for this could be: https://github.com/Viper007Bond/syntaxhighlighter/search?q=do_shortcode&ref=cmdform

This functions allows you to parse nested shortcodes:
http://www.sitepoint.com/wordpress-nested-shortcodes/

**Comment by aaronfc** [comment]
@fjorgemota I am moving this back to in-progress to make sure this is still on the radar :)
