### ISSUE TITLE
Data URI causes WP to fail save and preview

### ISSUE THREAD

**Issue by Tallmaris** [Automattic/syntaxhighlighter#34]
I don't know what's happening but when I try to enter some code similar to this:

[js]
$("img.placeholder").attr("src", "data:image/svg+xml;charset=utf8;base64," + encoded));
[/js]

It seems to hang wordpress:
- When I click the "Save Draft" the spinner just goes on and on until I get a browser error about page not responding. If I try to click "Preview" again the preview tries to load but it goes on forever before finally failing.
- The problem seems to be in the "data:image/" part. Even putting  "data :image/" will fix it (note the space between "data" and the colon). I tried escaping with '%3A' but the same thing happens.

As a workaround I tried to put a similar character, like a ꞉ (modifier letter colon, unicode  0xa789), but that may have other consequences in browser without fonts.

**Comment by Viper007Bond** [comment]
Some parser (regex or otherwise) is likely getting stuck on it. How odd. I'll see if I can track down why.

**Comment by alexsanford** [comment]
This appears to have been fixed, I cannot reproduce it.
