### ISSUE TITLE
Add Swift support

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/syntaxhighlighter#38]
https://github.com/alexgorbatchev/syntaxhighlighter/pull/314

http://wordpress.org/plugins/syntaxhighlighter-evolved-swift-brush/

**Comment by basememara** [comment]
The pull request link is broken. Is this something we can add without modifying the source code?

**Comment by renatho** [comment]
Closing since https://github.com/Automattic/syntaxhighlighter/pull/232 was merged.
