### ISSUE TITLE
Powershell double quote markup not working correctly

### ISSUE THREAD

**Issue by dzeleski** [Automattic/syntaxhighlighter#40]
Bug can be seen here (powershell): http://zeleskitech.com/2015/02/04/detect-httpd-high-cpu-usage-restart-collabnet-svn-fix-powershell/ 
On line 25, it seems to occur at the end on .... "$var.cpu"" The double double quotes at the end of the line dont seem to be terminating correctly.

Thanks,
Dylan

**Comment by Viper007Bond** [comment]
Sounds like it's an issue with the highlighting library rather than my WordPress implementation of it so you'll want to report this upstream at https://github.com/syntaxhighlighter/syntaxhighlighter
