### ISSUE TITLE
Add "inline" option?

### ISSUE THREAD

**Issue by shawaj** [Automattic/syntaxhighlighter#41]
Perhaps add an option the shortcodes to specify inline="true/false"

Default would be false, where the code will be unchanged from how it is now.

If you specify true, it would remove the gutter and put the code inline without display:block CSS.

This is really useful for displaying short single lines of code inline with the text.

Thanks

**Comment by Viper007Bond** [comment]
You'll want to submit a request like this upstream. I'm just the author of the WordPress implementation, not the actual highlighting package.

https://github.com/syntaxhighlighter/syntaxhighlighter

**Comment by shawaj** [comment]
Oh OK will do. Thanks for the great plugin

**Comment by Viper007Bond** [comment]
No problem. :)
