### ISSUE TITLE
Emoji links are shown in plaintext if code contains an emoticon

### ISSUE THREAD

**Issue by 2ndkauboy** [Automattic/syntaxhighlighter#43]
I haven't inspected how and when the emoticons in a post are converted into emojis. But currently, when some emoticons are present inside of the shortcode for the syntaxhighlighter, they are converted to the emojis, before the syntaxhighlighter converts the code into the HTML markup, so the link for the emoji is shown. Here is an example for such a highlighted code:

![emoji-she](https://cloud.githubusercontent.com/assets/1793177/8726477/c37dcfde-2bda-11e5-80f8-4a218475ab64.PNG)

**Comment by alexsanford** [comment]
This appears to have been fixed, I cannot reproduce.
