### ISSUE TITLE
Unwanted whitespace at the end of every snippet

### ISSUE THREAD

**Issue by spitoglou** [Automattic/syntaxhighlighter#48]
Wherever I try to use the highlighter I get some whitespace at the bottom. Take a look at the attached image:
![highligher](https://cloud.githubusercontent.com/assets/938287/9976953/9d498d10-5efe-11e5-839d-bc9df5deeaa9.png)
I tried changing the options, I resetted to the default ones, without any success so far...

**Comment by Viper007Bond** [comment]
Did you try switching WordPress themes to see if it goes away? Something in your theme's CSS is likely causing this.

If you link me to a post on your site where this is happening, it should be easy for me to figure out what CSS rule is causing it by using my browser's inspector tools.

**Comment by spitoglou** [comment]
I changed the theme and the problem went away. Thanks for the heads up.
