### ISSUE TITLE
[ps] becomes 1

### ISSUE THREAD

**Issue by staugur** [Automattic/syntaxhighlighter#50]
example:
my code(In the background):
      pt.append(str(psutil.disk_usage(psutil.disk_partitions()[ps][1])[-1])+'%')
but show:
     pt.append(str(psutil.disk_usage(psutil.disk_partitions()1[1])[-1])+'%')
why???

**Comment by Viper007Bond** [comment]
Can you link me to your site where this is happening so that I can see it in action? I suspect this is actually a bug with the highlighter and not my plugin.

**Comment by staugur** [comment]
https://saintic.com/1494.html

**Comment by Viper007Bond** [comment]
Sorry for the delay for looking at this, but I get a 404 at the URL now.

**Comment by staugur** [comment]
I have migrated to the site.
