### ISSUE TITLE
I hope this can set theme each block

### ISSUE THREAD

**Issue by HuJK** [Automattic/syntaxhighlighter#51]
I hope I can use code like this
[code theme="Emacs"]
gcc -o file a.c b.c c.c
[/code]

I want to use Default theme to show code, and use Emacs theme to show Console output.

**Comment by Viper007Bond** [comment]
Sorry but the highlighting library that I use, https://github.com/syntaxhighlighter/syntaxhighlighter, doesn't support that out of the box. I'd have to start wrapping each code block in a container and then modify all of the highlighter's CSS to only apply to code within containers matching it's theme. So technically doable, but a lot of work and not something I'm currently interested in doing.

I plan on eventually adding support for other highlighting scripts and I'd rather work towards that than spend time on this.

**Comment by HuJK** [comment]
Ok.
I hope add [code language="Console"] in syntaxhighlighter.

**Comment by Viper007Bond** [comment]
Console as in [Bash](https://en.wikipedia.org/wiki/Bash_%28Unix_shell%29)? That's already supported. :)
