### ISSUE TITLE
syntaxhighlighter broken on WP 4.4

### ISSUE THREAD

**Issue by datawookie** [Automattic/syntaxhighlighter#52]
Hi,

Firstly, thanks for this plugin. My blog revolves around code fragments, so use of this plugin is pretty central to everything I do.

I am not sure whether this is directly linked to WP 4.4, but I updated my site some time ago and have now noticed that a lot of my code (which is mostly R) is not being rendered properly by the plugin.

You can see examples here: http://www.exegetic.biz/blog/2015/01/download-option-chain-from-google-finance-in-r-an-update/. Quotes are being rendered as &quot; and the "<" character in the assignment operator is showing up as &lt;.

Thanks,
Andrew.

**Comment by Viper007Bond** [comment]
It's working fine for me: http://www.viper007bond.com/wordpress-plugins/syntaxhighlighter/ (my site is running WordPress trunk/alpha)

Can you please edit your post, switch to HTML view (not visual), and then copy/paste the contents into a [Gist](https://gist.github.com/)? I need something to test with if I'm going to attempt to reproduce your issue.

Thanks.

**Comment by datawookie** [comment]
Thanks for getting back to me so quickly. The code for that page can be found here: https://gist.github.com/DataWookie/f73722296f8ba7021a2d. Please let me know if there is any other information I can provide.

**Comment by datawookie** [comment]
Hi,

Just checking up if there has been any progress on this? I did find something interesting which might shed some light on the problem.

When I use markdown to format my code block there appear to be no HTML rendering problems. However, when I use the [code] shortcodes there are problems.

I have put some sample code here: https://gist.github.com/DataWookie/6caf02b5ba9f3791ba58. This example shows a problem with rendering double quotes when using shortcodes. Interestingly single quotes work fine with the shortcode but the R "<-" operator is rendered as "&lt;-".

I am using Wordpress 4.4.2. Please let me know if there's any way I can help with debugging this issue.

Thanks,
Andrew.

**Comment by Viper007Bond** [comment]
You appear to have a separate plugin that is causing this issue. Here's a screenshot using normal shortcodes, SyntaxHighlighter Evolved v3.1.13, and WordPress v4.5-alpha-36304:

![2016-02-08 19_03_13-shortcode test plugin development - firefox developer edition](https://cloud.githubusercontent.com/assets/406254/12906627/28688fc4-ce97-11e5-8e98-191158c10ecb.png)

Looks right to me unless I'm missing something.

**Comment by datawookie** [comment]
You were right: it must have been another plugin. Just not sure which one. I disabled all other plugins. Syntax highlighting then worked fine. I enabled each of the other plugins one at a time, hoping to find the culprit. Once I had enabled them all the highlighting was still working.

Very weird indeed.

But I am just happy that the issue is fixed. Thanks for the suggestion.
