### ISSUE TITLE
some help with language plugins

### ISSUE THREAD

**Issue by alex-harvey-z3q** [Automattic/syntaxhighlighter#57]
Hi there,

I'd like to adopt this project [here](https://github.com/en-jbrinkley/syntaxhighlighter-puppet) and update it for compatibility with Syntax Highlighter Evolved.  Any chance you know of instructions on how I can actually install the said plugin?  I'm a bit new to all this, and the author didn't respond.

**Comment by Viper007Bond** [comment]
That's a language "brush" for the JavaScript highlighting package "SyntaxHighlighter" which my plugin uses: https://github.com/syntaxhighlighter/syntaxhighlighter

To add that language to my WordPress plugin is pretty easy. I've written a guide here:

http://www.viper007bond.com/wordpress-plugins/syntaxhighlighter/adding-a-new-brush-language/

**Comment by alex-harvey-z3q** [comment]
Hi @Viper007Bond Belated thanks for the response.  I tried to follow your guide, although there's a bit of assumed knowledge that you know how to write Wordpress plugins in there.  Adapting your PHP code example looks straightforward enough, but how do I get this code onto my server?  Your plugin was easily installed via the Wordpress GUI.

**Comment by Viper007Bond** [comment]
Save it to a text file, upload it to your `/wp-content/plugins/` directory using FTP, and then rename it from `whatever.txt` to `whatever.php`.

GitHub is more meant for bug reports and feature requests than support help though, which I don't have time to provide. I'm afraid you're going to have to be on your own from here. Sorry. :(

**Comment by alex-harvey-z3q** [comment]
That's fair enough, and I appreciate the help you've offered so far.  By way of a feature or documentation request, it'd be great if it was documented somewhere how to take a brush such as the Puppet brush I'm planning to maintain and package it so that I can just install it via the Wordpress GUI.  Then anyone can use it, not just Wordpress developers.  Anyhow, no urgency.  I think I can at least get it working from here thanks to the help you've given me.

**Comment by Viper007Bond** [comment]
There's lots of documentation on how to write a WordPress plugin. See https://codex.wordpress.org/Writing_a_Plugin

Once you have it working, you can add it to WordPress.org: https://wordpress.org/plugins/about/

That will allow people to find it from the admin areas of all WordPress installs.
