### ISSUE TITLE
syntaxhighlighter Not included theme 

### ISSUE THREAD

**Issue by cepedit** [Automattic/syntaxhighlighter#60]
How can I add a WordPress theme?

**Comment by Viper007Bond** [comment]
If you want to add a new color theme for SyntaxHighlighter, see http://www.viper007bond.com/wordpress-plugins/syntaxhighlighter/adding-a-new-theme/

If you follow those instructions, it will show up in the theme dropdown.

Please use https://wordpress.org/support/plugin/syntaxhighlighter for further support.
