### ISSUE TITLE
Small project completion

### ISSUE THREAD

**Issue by mihdan** [Automattic/syntaxhighlighter#61]
1. Add class to wrapper DIV (`.syntaxhighlighter-wrapper`)
2. Add trigger after code highlighted (`syntaxhighlighter_complete`)

**Comment by Viper007Bond** [comment]
Isn't this already possible via existing classes? I'm pretty sure it is.

Regardless, item 2 isn't really feasible from my end because I'm not the author of the highlighting library. I do need to update it to the latest version however as my plugin is using an older version.

**Comment by mihdan** [comment]
1. http://screenshot.kobzarev.com/2016.10.10-001.jpg
2. ok

**Comment by Viper007Bond** [comment]
Yeah, that's all controlled by the highlighting library I use. I can't control that without forking it. I'd just hook onto the child `<div>` that has the class `syntaxhighlighter`.

Also I just realized for the 2nd item, you were talking about JavaScript. Check out the source code -- there might already be something that fires. I'm using version 3.x. The unminified code is here:

https://github.com/syntaxhighlighter/syntaxhighlighter/blob/3.0.83/scripts/shCore.js

**Comment by mihdan** [comment]
``` javascript
jQuery(function ( $ ) {
    /**
     * Добавить класс для обертки раскрашенного кода
     */
    setTimeout( function () {
        $('.syntaxhighlighter.nogutter').parent().addClass('syntaxhighlighter-wrapper');
    }, 2000 );
});
```

**Comment by mihdan** [comment]
Thanx
