### ISSUE TITLE
Feature Request: Code from GitHub

### ISSUE THREAD

**Issue by rhyous** [Automattic/syntaxhighlighter#62]
I love this plugin. I use it and recommend it. I would like to request a feature.

You know what would be an awesome feature? To not even had the code on the blog, except cached, but instead keep the code on github. 

It could be implemented as follows.

```
[csharp codeFromUrl="https://raw.githubusercontent.com/rhyous/SimpleArgs/master/Rhyous.SimpleArgs/Model/Argument.cs"]
[/csharp]
```

I took at look at your code base, but wouldn't be sure where or how to add this feature.

**Comment by rhyous** [comment]
Here is the code I used to display source from a URL on a blog post:

https://github.com/rhyous/GitHub-Code-Viewer-for-WordPress/blob/master/github.php

Now, I just need to figure out how to get syntax highlighter to highlight the code.

**Comment by Viper007Bond** [comment]
That sounds like cool functionality but I don't think it would fit well within my plugin. I think it would work better as a separate plugin, although it could require that my plugin be installed and build on top of it.
