### ISSUE TITLE
How to escape square brackets?

### ISSUE THREAD

**Issue by thomaslevesque** [Automattic/syntaxhighlighter#63]
It seems that text between square brackets are stripped from the highlighted code. For instance, in this code:

```
[diff "csharp"]
  xfuncname = ^[ \\t]*(((static|public|internal|private|protected|new|virtual|sealed|override|unsafe|async|partial)[ \\t]+)*[][<>@.~_[:alnum:]]+[ \\t]+[<>@._[:alnum:]]+[ \\t]*\\(.*\\))[ \\t]*$
```

the `[diff "csharp"]` part was stripped, maybe because it looks like a shortcode. Is there a way to escape it? As a workaround, I changed it to `[ diff "csharp"]`, but it's not ideal.

**Comment by Viper007Bond** [comment]
It was stripped because it _is_ a shortcode, although I thought I made it so that shortcodes weren't processed inside of code blocks.

Here's a guide on how to escape shortcodes so that they won't render:

http://www.viper007bond.com/2011/08/13/displaying-shortcodes/

**Comment by Viper007Bond** [comment]
Now that I think of it, it might not be possible to avoid that shortcode from being processed without escaping it as it's likely being handled before the one outside of it (the main one).

**Comment by thomaslevesque** [comment]
> Here's a guide on how to escape shortcodes so that they won't render:
> 
> http://www.viper007bond.com/2011/08/13/displaying-shortcodes/

Thanks, just what I needed!
