### ISSUE TITLE
Title being in capital letters

### ISSUE THREAD

**Issue by github-user-1** [Automattic/syntaxhighlighter#64]
If I set the title of a code the text get's capitalized - at least in my setup which is pretty much a standard wordpress installation. This is undesireable and I consider it a but as sometimes it's quite important (e.g. in the unix environments it's often crucial to know the exact spelling of e.g. file names: config.file is somthing else that CONFIG.FILE).

**Comment by Viper007Bond** [comment]
If you visit Settings → SyntaxHighlighter in your admin area and scroll down, are you able to reproduce this? I'm not.

I suspect some CSS in your theme is at fault and using styling to make the text appear uppercase. You should be able to fix it by adding some CSS to your theme that targets the SyntaxHighlighter title and unapplies the rule that's making it uppercase.
