### ISSUE TITLE
Broken HTML when switching between text and visual

### ISSUE THREAD

**Issue by mpgo13** [Automattic/syntaxhighlighter#68]
Steps to reproduce:

1. Open tinymce editor in text mode

2. Add the following example
    ```
    <ul>
      <li>[javascript][/javascript]</li>
      <li>[java][/java]</li>
    </ul>
    ```

3. Switch to visual tab

**Expected result**: Two items of the unordered list with the given shortcodes
**Actual result**: One item and broken HTML.

![image](https://user-images.githubusercontent.com/1078584/28991741-00af762e-79d0-11e7-8319-cf0c8d16cfbf.png)

**Comment by Viper007Bond** [comment]
Thanks for the bug report! I'll reply on #69.
