### ISSUE TITLE
Yandex Metrica Problem

### ISSUE THREAD

**Issue by SeLoRe** [Automattic/syntaxhighlighter#71]
Hi,

When I activate that plugin yandex metrica codes doesn't work, do you have a known solution about that.

**Comment by Viper007Bond** [comment]
What are "yandex metrica codes" ?

**Comment by SeLoRe** [comment]
It is an analytics service like google analytics.  https://metrica.yandex.com  When I activate that plugin it stops to work.

**Comment by SeLoRe** [comment]
I found a code difference now. When I activate the plugin it adds end of the yandex metrica code style="outline: none;"  maybe problem is because of this.

Edit: I checked again there is no difference problem is another thing. I wait your response.

**Comment by Viper007Bond** [comment]
Can you give me some sample tracking code to test with? Also how are you adding it to your site? Have you manually added it to your theme's footer file? Or is a plugin adding it somewhere?

**Comment by SeLoRe** [comment]
I have a demo website I can give you usename and pasword for check it closer but how will I give ?  I added my tracking code as a footer widget using with custom html. My code is below

```
<!-- Yandex.Metrika informer -->
<a href="https://metrika.yandex.com.tr/stat/?id=46691274&amp;from=informer"
target="_blank" rel="nofollow"><img src="https://informer.yandex.ru/informer/46691274/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
style="width:88px; height:31px; border:0;" alt="Yandex.Metrica" title="Yandex.Metrica: bugün için veriler (görüntülemeler, ziyaretler ve tekil ziyaretçiler)" class="ym-advanced-informer" data-cid="46691274" data-lang="tr" /></a>
<!-- /Yandex.Metrika informer -->

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter46691274 = new Ya.Metrika({
                    id:46691274,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/46691274" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
```

**Comment by Viper007Bond** [comment]
That should be enough to try to reproduce your issue. I'll let you know how it goes. :)

**Comment by SeLoRe** [comment]
Is there any news ?

**Comment by Viper007Bond** [comment]
No, I've been busy. I was in the hospital yesterday and today is a national holiday. I'll update this ticket when I have something to report.

**Comment by SeLoRe** [comment]
I found now what is the difference in metrica code.

Before the plugin is activated

`(w[c] = w[c] || []).push(function() {`

After the plugin is activated

`(w = w || []).push(function() {`

**Comment by Viper007Bond** [comment]
Can you try adding this to your theme's `functions.php` file?

```
add_filter( 'syntaxhighlighter_shortcodes', function( $shortcodes ) {
    unset( $shortcodes[ array_search( 'c', $shortcodes ) ] );

    return $shortcodes;
} );
```

**Comment by SeLoRe** [comment]
Yeah it worked like a charm. You can think fix that on next update, because I tried to add my metrica code in post between [php]metrica[/php] it removed this snippet `[c]` as it is at the footer widget. Thank you so much for your interest, this is my favorite highlighter plugin anymore ;)

**Comment by Viper007Bond** [comment]
`[c]` is being parsed as a shortcode by my plugin. I made the mistake of making too many languages as shortcodes, instead of just having people do `[code lang="php"][/code]`.

The issue is if I remove `c` as a shortcode, it'll break all existing uses of it by people, but I just might do it anyway due to stuff like this.

**Comment by SeLoRe** [comment]
Oky bro, thank you. You can close the issue.
