### ISSUE TITLE
Old Links

### ISSUE THREAD

**Issue by ghost** [Automattic/syntaxhighlighter#74]
It seems like the website http://alexgorbatchev.com/ has changed alot resulting in many 404 errors in the description texts and wiki links. this should be changed

**Comment by Viper007Bond** [comment]
Yeah, and there's also a newer version of the highlighting library too: https://github.com/syntaxhighlighter/syntaxhighlighter

It'll require some rewriting of my plugin to use though. My plugin just needs a general refresh where I tackle all of this.
