### ISSUE TITLE
Visual editor support

### ISSUE THREAD

**Issue by mundschenk-at** [Automattic/syntaxhighlighter#76]
Currently, `<`and `>` get entity encoded when switching between the visual and HTML tabs of the post editor. I know that this is a known bug, but very annoying. (I'm pretty certain it is fixable, though.)

**Comment by Viper007Bond** [comment]
My plugin includes a plugin for the visual editor that is supposed to handle switching between the two:

https://github.com/Viper007Bond/syntaxhighlighter/blob/master/syntaxhighlighter_mce-4.js

But it can be fragile sometimes and my recommendation is to just avoid switching between editors when dealing with code. The visual editor can be too smart for its own good.

**Comment by mundschenk-at** [comment]
Yes, but the problem happens not just on switching, but on loading. Or maybe it happens just on loading and the case needs to be handled there as well? I didn't yet investigate in that direction.

**Comment by Viper007Bond** [comment]
Gonna close this since TinyMCE has been replaced by Gutenberg in core. Blocks are so much better.
