### ISSUE TITLE
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by mersadk** [Automattic/syntaxhighlighter#77]
I'm using Virtue Premium theme and Syntax Highlighter can't be initialized. In Chrome console there is following error:

> Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

I assume Virtue Premium theme is affecting custom style elements placement.

To fix this just replace `document.getElementsByTagName("head")[0]` with `document.getElementById("syntaxhighlighteranchor").parentNode` in `syntaxhighlighter.php` (lines 709 and 724).

This fix should work in all other cases as well.

**Comment by Viper007Bond** [comment]
Hmm, if I'm reading this correctly, there's no `<head>` tag? That seems... odd.

**Comment by mersadk** [comment]
There is `<head>`tag, but element `<style type="text/css" id="syntaxhighlighteranchor"></style>` is for some reason rendered in `<body>`.

**Comment by Viper007Bond** [comment]
Sounds like the theme has `<?php wo_head(); ?>` in the wrong spot.

**Comment by mersadk** [comment]
It renders it correctly inside `<head>` but when I run `document.getElementById("syntaxhighlighteranchor").parentNode` in Chrome console, it returns `<body>` as parent, I'm not sure at which point it rearranges styles.

**Comment by Viper007Bond** [comment]
If you temporarily switch to the Twenty Seventeen theme, does it work correctly?

**Comment by georgik** [comment]
I hit the similar problem. The plugin was working ok for years, but after upgrade to WP 5.0.3 and Highlighter 3.5.0 with Google Chrome 70 highlighting stopped to work.

Workaround:
I changed: 
`document.getElementsByTagName("head")[0].insertBefore...`
to `document.getElementsByTagName("head")[0].appendChild`
on lines 959 and 974 in th e file sysntaxhighlighter.php, the plugin starts to work again.

Here is sample page with code: https://georgik.rocks/how-to-write-game-with-vue-js-sokoban-part-4-move-avatar-by-mouse-click/

**Comment by Viper007Bond** [comment]
That's odd as the `<style>` tag is correctly inside of your `<head>`.

Regardless though, I'll fix up that ancient code to be more robust.

**Comment by georgik** [comment]
@Viper007Bond Thank you for quick fix.
The strange tag `<style>` came with Emojis in WP 4.2 it's stored in `wp-includes/formatting.php`. Thank you for pointing that out. These emojis were causing also unnecessary requests on server. So I disabled this functionality by disable-emojis plugin.

**Comment by Viper007Bond** [comment]
I meant my placeholder anchor `<style>` tag but regardless, should be fixed in the next release. :)
