### ISSUE TITLE
Parsing stripping out large blocks of code

### ISSUE THREAD

**Issue by j2kun** [Automattic/syntaxhighlighter#79]
The following:

```
  let translatedMidpoints = [];
  for (let i = 0; i < translatedTargets.length; i++) {
    let targetList = translatedTargets[i];
    translatedMidpoints.push(targetList.map(t => t.midpoint(assassin)));
  }
```

Is replaced with the following

```
// compute the midpoints between the assassin and each translate
let translatedMidpoints = [];
for (let i = 0; i  t.midpoint(assassin)));
}
```

It seems the missing string is being interpreted as an HTML tag and stripped:

```
< translatedTargets.length; i++) {
    let targetList = translatedTargets[i];
    translatedMidpoints.push(targetList.map(t =>
```

Live demo: https://jeremykun.com/2018/07/24/visualizing-an-assassin-puzzle/

This plugin is used by Wordpress.com, and I pay them a monthly fee to host my blog. Code support and latex support have been broken on Wordpress since I started blogging eight years ago. Judging by the open issue from 2014 to "add unit tests," I finally see why it's been so janky. This is just one of many, many bugs I've encountered over the years. (In case you're interested, another is that "Ctrl-Z" often results in a call to what I assume is `htmlspecialchars` on the code snippet and/or the entire buffer.)

I think it's about time Automattic invest in fixing this.

**Comment by alexsanford** [comment]
This appears to have been fixed, I cannot reproduce the issue. Please feel free to open additional issues for reproducible bugs that you find.

**Comment by j2kun** [comment]
Hi @alexsanford,

Could you point me to the commit in which it was fixed?

Below is a recording of the reproduction, made today from an empty new post draft. The rendered page contains the exact output stated two years ago.

I cannot emphasize enough that this has been a _decade_ long problem for me.

![repro-2](https://user-images.githubusercontent.com/2467754/76686914-8c57db80-65dc-11ea-92c2-bf72fbb06c14.gif)

**Comment by alexsanford** [comment]
@j2kun Thanks for the clarification!

Since you aren't using the shortcodes provided by this plugin (e.g. `[code]` or `[js]`), I would say that the problem is coming from somewhere else. Looks like you're on the classic editor of WordPress.com, perhaps that is erroneously stripping out some HTML-like strings?

I would recommend getting in touch with WordPress.com support for this problem. If you are able to reliably reproduce this issue using this plugin's shortcodes and/or block, please feel free to post a bug report here, or post on the [support forum](https://wordpress.org/support/plugin/syntaxhighlighter/) for help.

**Comment by j2kun** [comment]
There are bugs with [code] as well, it inserts some random html snippets.

I've tried asking Wordpress support many times over the years. Sounds like you're telling me it's a lost cause at this point.

**Comment by alexsanford** [comment]
> There are bugs with [code] as well, it inserts some random html snippets.

If there are other bugs with reproducible steps that directly involve one of our shortcodes, or our Block in the Block Editor, please feel free to post another bug here, or reach out on the support forum.
