### ISSUE TITLE
SyntaxHighlighter Hangs in the browser and Firefox offers to stop a long running script

### ISSUE THREAD

**Issue by laszlocsontos** [Automattic/syntaxhighlighter#80]
**Steps to reproduce**

- Create a new post with the following content

```
[xml]
<project>

  <properties>
    <spring-cloud.version>Finchley.SR1</spring-cloud.version>
    <spring-cloud-kubernetes.version>0.3.0.RELEASE</spring-cloud-kubernetes.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-commons</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-kubernetes-core</artifactId>
    </dependency>

  </dependencies>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-kubernetes-dependencies</artifactId>
        <version>${spring-cloud-kubernetes.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

</project>
[/xml]
```

- Click _Preview_
- Notice that the preview and pages hung

**Workaround**

Use SyntaxHighlighter 2.x

**Environment**

Wordpress: 4.9.8
SyntaxHighlighter Plugin: 3.2.1

**SyntaxHighlighter Settings**

* Version: 3.x
* Color Theme: RDark
* Display line numbers
* Automatically make URLs clickable
* Use smart tabs allowing tabs being used for alignment
* Wrap long lines (v2.x only, disabling this will make a scrollbar show instead)
* Starting Line Number: 1
* Line Number Padding: Off
* Tab Size: 4

**Comment by ChrisHardie** [comment]
Are you using any performance optimization plugins on your site that do Javascript minification and/or concatenation? I recently had an issue where the minified, concatenated versions of the JS from this plugin would cause all browsers to hang on any page where they were present. Excluding them from that fixed the issue. Similar reports in https://wordpress.org/support/topic/conflict-with-w3tc-js-minify-cause-chrome-browser-frozen/ and https://wordpress.org/support/topic/not-working-with-better-wordpress-minify/

**Comment by alexsanford** [comment]
This appears to be fixed, I cannot reproduce the issue.
