### ISSUE TITLE
Broken as of Oct. 2018 update

### ISSUE THREAD

**Issue by tlhintoq** [Automattic/syntaxhighlighter#82]
As seen even on the homepage:
https://alex.blog/wordpress-plugins/syntaxhighlighter/

The plugin is broken as of the October 2018 Word Press update.  Others have mentioned it there, but I don't see it mentioned here in the issues; which surprises me.  So creating an issue for it.

![image](https://user-images.githubusercontent.com/11351506/48008013-d24a8880-e0e6-11e8-8853-c0594e6ce4c1.png)

**Comment by Viper007Bond** [comment]
Thanks for reporting!

This is a bug caused by Gutenberg. I disabled the plugin on my site and it's working now. It won't affect WordPress 5.0.

More details here: https://meta.trac.wordpress.org/ticket/3907#comment:3
