### ISSUE TITLE
Notice: Undefined index: language

### ISSUE THREAD

**Issue by mimosafa** [Automattic/syntaxhighlighter#85]
With Gutenberg and used 'syntaxhighlighter/code' block, but these code were not be highlited.

And i saw

```
Notice: Undefined index: language in /var/www/html/wp-content/plugins/syntaxhighlighter/syntaxhighlighter.php on line 361
```

Is this block unimplemented yet ?

--

WordPress 4.9.8
Gutenberg 4.5.1
SyntaxHighlighter Evolved 3.3.1

**Comment by Viper007Bond** [comment]
No it should work fine. I'll investigate. Thanks for the report!

**Comment by Viper007Bond** [comment]
Fixed in https://github.com/Viper007Bond/syntaxhighlighter/commit/84796127b86d3acf5a1cfebd36270bb989b783e6. You need to select a code language from the block's settings, but now it'll properly default to plain text.

**Comment by mimosafa** [comment]
Oh! sorry... [I also overlooked that](https://github.com/Viper007Bond/syntaxhighlighter/issues/86#issuecomment-442541013).
It's works well! And thank you for fixing.

**Comment by Viper007Bond** [comment]
I think I'll change the placeholder text to mention that, and maybe also add the ability to set a default language.
