### ISSUE TITLE
No syntax highlighting when using the new block

### ISSUE THREAD

**Issue by jeherve** [Automattic/syntaxhighlighter#86]
WP: 5.1-alpha
Gutenberg: 4.5.1
SyntaxHighlighter Evolved: 3.3.1

- https://jeremy.hu/jetpack-photon-control-images/

For some reason the block does not get syntax highlighted, while non-blocks still do.

**Comment by jeherve** [comment]
It works now, don't mind me! I had missed the block's inspector controls, and that you had to set the language there!

**Comment by Viper007Bond** [comment]
Yeah, it defaults to plain text but should still render the fancy line numbers and stuff.
