### ISSUE TITLE
Line number shifted with some themes

### ISSUE THREAD

**Issue by reynum2** [Automattic/syntaxhighlighter#87]
Hello,
when I try some wordpress themes, sometime I have a shift between lines and numbers as you can see in this picture.

![problem_with_syntax_hilighter](https://user-images.githubusercontent.com/11191723/49221641-08bfae80-f3da-11e8-8577-dcf60a145eaf.png)

The actual theme is "Fooding"

I fix this by edit the file
wordpress/wp-content/plugins/syntaxhighlighter/syntaxhighlighter3/styles/shCore.css

and comment the line :
vertical-align: baseline !important

**Comment by Viper007Bond** [comment]
I didn't write that CSS, but I'm worried that making that change would break other themes. :(
