### ISSUE TITLE
Brushes not loading when turned to reusable block

### ISSUE THREAD

**Issue by david-binda** [Automattic/syntaxhighlighter#91]
`enable_brushes_used_in_blocks` function bails early in case it does not find `syntaxhighlighter/code` block:

https://github.com/Viper007Bond/syntaxhighlighter/blob/fcc401df7b93e60d19eadd185723728250dfc039/syntaxhighlighter.php#L358

But, in case `syntaxhighlighter/code` is turned into a reusable block, this check fails. So perhaps it's necessary to inspect all reusable blocks as well?

**Comment by Viper007Bond** [comment]
Thanks for the report! I forgot to play around with and test reusable blocks. I'll work on getting a fix out!
