### ISSUE TITLE
wordpress blog display got messed up when more than one code blocks are used

### ISSUE THREAD

**Issue by bachoang** [Automattic/syntaxhighlighter#95]
I am using SyntaxHighlighter Evolved wordpress plugin version 3.5.0 on a Wordpress site (version 5.0.2).  The plugin works great if there is only one code snipplet:
[code language="powershell"]
…
[/code].

The blog display got broken when I start using more than 1 code snipplet.  In my blog, I have about 4 code snipplets spread throughout the blog.  Some of the display simptoms when more than 1 code block is used:

1) The horizontal scroll bar for the code block disappears and text starts wrapping
2) The green line (gutter) got chopped off early before the end of my codes snipplet
3) the gutter line numbering starts to fall out of place.  It starts at 1 on a blank line where there is no code
4) Starting from the 1st code block it displays the rest of my blog text (even outside of a code block) in a narrow light grey background area (I think it puts all of my blog content following the 1st code block into a pre element)

**Comment by Viper007Bond** [comment]
Sounds like a theme issue. Here's an example from my site where multiple code blocks are used:

https://alex.blog/category/coding/

The highlighting package I use has `!important` declarations in its CSS in an attempt to prevent other style rules from affecting the code blocks, but as you can see it isn't perfect. :(

You should be able to verify this by previewing a different theme on your site using the customizer.

To fix it (assuming you don't want to just switch themes), you'll need to use your browser's element inspector to see what styling rules are causing the issues and then setting rules for `.syntaxhighlighter` that overrides your theme (`auto` perhaps).
