### ISSUE TITLE
Leading spaces removed by WordPress 5 editor

### ISSUE THREAD

**Issue by pkubowicz** [Automattic/syntaxhighlighter#97]
When I edit a post and manually type:
```
[code language="css"]
a {
   color: blue;
}
[/code]
```
then click any of: "Preview" or "Update"

the in the moment of clicking leading spaces are removed from my code by the WordPress editor, so I get:
```
[code language="css"]
a {
color: blue;
}
[/code]
```

This breaks the whole idea of posting source code to WordPress.

I cannot find and instructions how to prevent this behaviour by reading https://wordpress.org/plugins/syntaxhighlighter/ or https://en.support.wordpress.com/code/posting-source-code/

WordPress 5.0.2, SyntaxHighlighter Evolved 3.5.0

Tested on both Firefox 64.0 and Chromium.

**Comment by Viper007Bond** [comment]
Are you using the new block editor (Gutenberg) or have you reverted back to the Classic Editor? If you're using the new block editor, what block are you typing this into?

**Comment by pkubowicz** [comment]
It's a fresh installation of WordPress 5 with default settings used, so I am using Gutenberg. I put the code to the "Hello World" post, the bug appears when I write text in new posts, so I guess it's the default block type.

**Comment by Viper007Bond** [comment]
Try using the block my plugin provides instead. It's called "SyntaxHighlighter Code".

**Comment by pkubowicz** [comment]
Sorry for confusion. The code of my post did not contain any blocks. The bug happens only when blocks are not used and only when I click 'Preview' from Code Editor. A workaround is to use
```
<pre>[code language="css"]
a {
   color: blue;
}
[/code]</pre>
```
which preserves whitespace, but creates invalid resulting HTML, which breaks page layout.

**Comment by Viper007Bond** [comment]
This seems to be an issue with WordPress itself. When you're using the "Code Editor" view, it seems to strip leading spaces.

Try switching to the "Visual Editor" view using the three vertical dots in the upper-right and it'll work as expected, especially if you switch from using the shortcode to using a block instead. Blocks are so much better than shortcodes. :)

![firefox_16pwftiq8p](https://user-images.githubusercontent.com/406254/50880470-52b19200-1393-11e9-8ec0-b35240b6ea8a.png)

**Comment by alexsanford** [comment]
This appears to have been fixed, I cannot reproduce the issue.
