### ISSUE TITLE
Something wrong with &amp; in Gutenberg blocks

### ISSUE THREAD

**Issue by kedixa** [Automattic/syntaxhighlighter#98]
I'm using WordPress 5.0 and SyntaxHighlighter Evolved 3.5.0.
It seem wrong when there are '&' and '<' characters in the code. For example, if I write "a && b < c" in the code block, it becomes "a &amp;amp;&amp;amp; b < c;" in my post; if I write "&amp;amp;" in the code block, it becomes "&" in my post.

**Comment by Viper007Bond** [comment]
This is an issue with the core code block too. I'm waiting on some feedback before trying to address it.

See https://github.com/WordPress/gutenberg/issues/13218

**Comment by kedixa** [comment]
OK, Thank you very much!

**Comment by Warlib1975** [comment]
Yes, the same problem. And also after the last WP update the problem with quotes in the С++ code: all quotes shows as "&quot".

![image](https://user-images.githubusercontent.com/11045291/51423038-65656b80-1bca-11e9-84b5-e29a81f3cad4.png)

**Comment by Warlib1975** [comment]
Hello, colleagues,

do you have some decision on how to workaround the problem with &quot; and &amp;lt; and &gt. All codes in my blog now impossible to read. It's look like a garbage. :-( Here is the example of the JSON file visualization:
 
![image](https://user-images.githubusercontent.com/11045291/51783101-d2867d00-2145-11e9-8991-fdca925e6354.png)

**Comment by reekes** [comment]
Same here, my code is unreadable after syntax highlighting. If this isn't fixed soon, I'll have to find an alternative.

PS - I'm on WordPress 5.0.3 and I am *not* using Gutenberg

**Comment by Viper007Bond** [comment]
I've been in the hospital lately but plan on looking into this soon.

**Comment by Viper007Bond** [comment]
I'm still able to reproduce this issue in the `core/code` Gutenberg block with WordPress 5.0.3 and both the Gutenberg plugin disabled (core code) and enabled (newer code).

I'm really not quite sure what to do. :(

**Comment by Warlib1975** [comment]
> I'm still able to reproduce this issue in the `core/code` Gutenberg block with WordPress 5.0.3 and both the Gutenberg plugin disabled (core code) and enabled (newer code).

I try another syntax highlighting plugin: https://www.wordpress.org/plugins/enlighter/ The problem with it with Gutenberg is similar, but the situation is a little bit better. At least after saving it shows the code for readers ok. But when I return for editing page, the block with code shows as broken and impossible to edit its. :-( I created the issue in the Gutenberg Github with information, that for now there is no any working code highlighting plugin working properly with Gutenberg, so, it seems, the problem with Gutenberg.

**Comment by Warlib1975** [comment]
> I've been in the hospital lately but plan on looking into this soon.

Get well!!! You wrote the beautiful plugin, very useful.

**Comment by Warlib1975** [comment]
> Same here, my code is unreadable after syntax highlighting. If this isn't fixed soon, I'll have to find an alternative.

Unfortunately, it seems that there is no any working syntax highlighter plugin working with Gutenberg. Only in classic mode they work ok.

**Comment by iamntz** [comment]
Hey guys, I've encountered this issue as well and I figured out that I can fix it on existing codebase, using a filter:

```
add_filter('syntaxhighlighter_htmlresult', function($html) {
	return preg_replace('/&amp;([^;]+;)/', '&$1', $html);
});
```

Basically the pattern is the same: the wrongly escaped string is transformed from `&foo;` to `&amp;foo;`. 

This _may_ lead to some weird effects in some edgecases, but for _my_ requirements this works just fine.

**Comment by David-Else** [comment]
@iamntz I don't know Wordpress or PHP coding, but I am a JS developer and can work things out. Could you explain how I can add your filter and make things work? Cheers!

**Comment by iamntz** [comment]
Just add that snippet to your `functions.php` file.

**Comment by David-Else** [comment]
@iamntz THANKS!!! It worked :)

If people find any problems with the filter or it gets fixed in core/original plugin, let's add a comment to this thread.

**Comment by David-Else** [comment]
@iamntz I spoke too soon!!! all the &amp;quot; came back  when I came back to the post later on after closing the browser... now I dare not update the page again. How is this nonsense happening?!

What was working 20 mins ago in the Gutenberg editor and on the rendered page:

`sudo sh -c 'echo -e "\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'`

degenerated into:
`
sudo sh -c 'echo -e &amp;quot;[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc&amp;quot; &amp;gt; /etc/yum.repos.d/vscode.repo'`

I am hitting Update every-time as the broken Gutenberg editor in WP 5.1 does not preview https://github.com/WordPress/gutenberg/issues/12617

I added the snippet to the child theme functions.php, my code snippets are in Custom HTML blocks and look like:

`[bash]hostnamectl set-hostname yourhostname[/bash]`

[rant]I really do hate WordPress, if I had the time I would learn Drupal, it is just not a professional product, wish I knew better when I started out.[/rant]

**Comment by iamntz** [comment]
@David-Else: I don't think i understand what you're doing: you're using shortcodes to insert code samples? Why not using syntax block? 

![](https://img.iamntz.com/2019-03-10_17h23_03.jpg)

As far as I can tell, the issue _do_ exists, but is only if you're using shortcodes :)

**Comment by iamntz** [comment]
A small update: same regex applied to shortcodes will lead to the correct result on frontend, but backend will still look scrambled:

```
add_filter('syntaxhighlighter_precode', function ($code, $atts, $tag) {
	return preg_replace('/&amp;([^;]+;)/', '&$1', $code);
}, 10, 3);
```

**Comment by iamntz** [comment]
I think I fixed 😬 


```php
// functions.php
function ntz_fix_syntax_highlighter($content)
{
	return preg_replace('/&amp;([^;]+;)/', '&$1', $content);
}

add_filter('content_save_pre', 'ntz_fix_syntax_highlighter');
add_filter('syntaxhighlighter_htmlresult', 'ntz_fix_syntax_highlighter');
add_filter('syntaxhighlighter_precode', 'ntz_fix_syntax_highlighter');
```

What this will do is to replace the doubled encoded strings on: 

1. post save
2. Code from Gutenberg blocks
2. Shortcodes (Gutenberg or TinyMCE)

The last two filters are needed only for legacy (i.e. if you don't want to go and update all existing posts).

**Comment by David-Else** [comment]
@iamntz Great work, thanks for the help!! I have changed to use the `[code][/code]` block instead of the custom html block as you recommended, but inside that I need to use `[bash][/bash]` or I get no syntax highlighting.

If I use the SyntaxHighlighterCode block I get no good results with or without the shortcode.

Thing seem to work now, so just to confirm, if I use `[code] `blocks and shortcodes (i seem to need them for it to work) I should use?:
```
function ntz_fix_syntax_highlighter($content)
{
	return preg_replace('/&amp;([^;]+;)/', '&$1', $content);
}

add_filter('content_save_pre', 'ntz_fix_syntax_highlighter');
```
(no backward compatibility needed)

**Comment by iamntz** [comment]
You need to use either shortcodes OR syntax blocks, not both.

As for highlight: you did selected the language, right? https://img.iamntz.com/2019-03-11_05h22_25.mp4

**Comment by David-Else** [comment]
@iamntz Thanks, I have always used shortcodes, did not see the language option!

**Comment by David-Else** [comment]
@iamntz Thanks! With your `ntz_fix_syntax_highlighter` function and using the right block things now work great.

**Comment by heyquentin** [comment]
hey @iamntz 
I implemented your function to fix the issue with & on my site but it looks like it only works for one &. If I have code that has two & side by side (command1 && command2) it displays 
command1 && amp; command2

Got any suggestions?

**Comment by iamntz** [comment]
I think you could just `str_replace` for that:

```
function ntz_fix_syntax_highlighter($content)
{
	$content = str_replace('&amp;&amp;', '&&', $content);
	$content = preg_replace('/&amp;([^;]+;)/', '&$1', $content);

	return $content;
}
```

**Comment by heyquentin** [comment]
@iamntz It looks like everything is working now. Thanks a ton for your help!

**Comment by apoorvlathey** [comment]
@iamntz Thanks. Works Fine !

**Comment by dandago** [comment]
I ran into this problem last week, with `&` turning into `&amp;` in WordPress 5.x with SyntaxHighlighterEvolved. Could we have an official fix please? It seems widespread and quite a serious deal-breaker. I'd rather not resort to hacks for something like this.

**Comment by vicente-somnis** [comment]
Thank you very much, iamntz, for `ntz_fix_syntax_highlighter` function. All works fine now.

**Comment by ninjazhai** [comment]
> I think you could just `str_replace` for that:
> 
> ```
> function ntz_fix_syntax_highlighter($content)
> {
> 	$content = str_replace('&amp;&amp;', '&&', $content);
> 	$content = preg_replace('/&amp;([^;]+;)/', '&$1', $content);
> 
> 	return $content;
> }
> ```

I added this code to functions.php of my child theme and it worked. Thank you so much @iamntz!

**Comment by mayanksdudakiya** [comment]
@iamntz Thanks. Working for me

**Comment by idarek** [comment]
String replace didn't work for me. 
I have put same code into Advanced Gutenberg block [code] and is displayed correctly, but in SyntaxHighlighter not.

**Comment by mayanksdudakiya** [comment]
@idarek Following code is working for me. Add the following code into the function.php file of your child theme.

```
/*@ Resolve &amp; issue of syntax highlighter */
add_filter('syntaxhighlighter_htmlresult', function($html) {
    return preg_replace('/&amp;([^;]+;)/', '&$1', $html);
});
```

**Comment by khitrenovich** [comment]
It still happens in 2021 (and Wordpress 5.5.3). Fortunately, the solution above still works too.

**Comment by donnapep** [comment]
This was fixed by https://github.com/Automattic/syntaxhighlighter/pull/160 in 3.6.0.
